import Head from "next/head";
import Header from "../components/Header";

export default function Home() {
  return (
    <div className={{ background: "red" }}>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
    </div>
  );
}
