import axios from "axios";
import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Result from "../components/Result";
import request from "../utils/request";

export default function Home({results}) {
  // console.log('get server side rendering',results)
  return (
    <div className={{ background: "red" }}>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
      <Nav />
      <Result request={results}/>
    </div>
  );
}

export async function getServerSideProps(context){
  const genre = context.query.genre //geting query params
  const requestres = await axios
                                .get(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrending.url}`)
                                .then(res=>res.data)
                                .catch(e=>console.log('error in fetching data',e))
  // const requestres = await axios.get(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrending.url}`).then(res=>res.json())

  return{
    props:{
      results:requestres.results
    }
  }
}
