import Head from "next/head";
import Header from "../components/Header";
<<<<<<< HEAD
import Nav from "../components/Nav";
import Result from "../components/Result";
import request from "../utils/request";

export default function Home({results}) {
  // console.log('get server side rendering',results)
=======

export default function Home() {
>>>>>>> 82e46c11347a117223c5f73eeb3ad4f5655fcaf4
  return (
    <div className={{ background: "red" }}>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header />
<<<<<<< HEAD
      <Nav />
      <Result request={results}/>
    </div>
  );
}

export async function getServerSideProps(context){
  const genre = context.query.genre //geting query params
  const requestres = await fetch(`https://api.themoviedb.org/3${request[genre]?.url || request.fetchTrending.url}`).then(res=>res.json())

  return{
    props:{
      results:requestres.results
    }
  }
}
=======
    </div>
  );
}
>>>>>>> 82e46c11347a117223c5f73eeb3ad4f5655fcaf4
